
server.port=5054

spring.application.name=ManageR

spring.datasource.url=jdbc:postgresql://localhost:5432/manager
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saideshmukh283@gmail.com
spring.mail.password=qqfpxnpthnrmdfba
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.api.key=rzp_test_ZdAUSfkVr4d1Ez
razorpay.api.secret=B3RmqHsfDmYfTkGaejTK9dKe